import type { Metadata } from "next";
import localFont from "next/font/local";
import Link from "next/link";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Portal de eventos",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex h-screen bg-gray-50">
          {/* Menu Lateral */}
          <aside className="w-64 bg-gray-800 text-gray-100">
            <div className="p-6 font-bold text-teal-500 text-2xl">
              fest-fy.com
            </div>
            <nav>
              <ul>
                <li className="px-4 py-2 hover:bg-teal-500 hover:text-white">
                  Dashboard
                </li>
                <li className="px-4 py-2 hover:bg-teal-500 hover:text-white">
                  Espaços
                </li>
                <li className="px-4 py-2 hover:bg-teal-500 hover:text-white">
                  Reservas
                </li>
                <li className="px-4 py-2 hover:bg-teal-500 hover:text-white">
                  Usuários
                </li>
                <li className="px-4 py-2 hover:bg-teal-500 hover:text-white">
                  Configurações
                </li>
                <li className="px-4 py-2 hover:bg-teal-500 hover:text-white">
                  <Link
                    href="/login"
                  >
                    Login
                  </Link>
                </li>

                <li className="px-4 py-2 hover:bg-teal-500 hover:text-white">
                  <Link
                    href="/signUp"
                  >
                    Criar conta
                  </Link>
                </li>

                <li className="px-4 py-2 hover:bg-teal-500 hover:text-white">
                  <Link
                    href="/create"
                  >
                    Formulário principal
                  </Link>
                </li>
              </ul>
            </nav>
          </aside>

          {/* Conteúdo Principal */}
          <main className="flex-1 p-8">
            <header className="text-3xl font-semibold text-gray-700 mb-8">
              Dashboard
            </header>

            {children}
            <section className="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-3">
              {/* Cards de exemplo */}
              <div className="p-6 bg-white rounded-lg shadow-md">
                <h2 className="text-xl font-medium text-teal-600">Espaços Disponíveis</h2>
                <p className="mt-4 text-gray-600">Gerencie e visualize os espaços para eventos.</p>
              </div>
              <div className="p-6 bg-white rounded-lg shadow-md">
                <h2 className="text-xl font-medium text-teal-600">Reservas Recentes</h2>
                <p className="mt-4 text-gray-600">Veja as últimas reservas confirmadas.</p>
              </div>
              <div className="p-6 bg-white rounded-lg shadow-md">
                <h2 className="text-xl font-medium text-teal-600">Estatísticas de Uso</h2>
                <p className="mt-4 text-gray-600">Acompanhe as estatísticas de uso da plataforma.</p>
              </div>
            </section>
          </main>
        </div>
      </body>
    </html>
  );
}
